### ISSUE TITLE
Table cells don't line up right

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#10]
Just saw that the cells don't quite line up. Maybe just the cellspacing in the .css file?

![image](https://github.com/skadogg/personal-tv-guide/assets/19212961/a32051ca-633e-4f5d-ae50-85f2051ba919)

**Comment by perriDplatypus** [comment]
I think this might just be a result of how HTML makes tables. The lines on the left are thicker because there are overlapping table elements in that area. On the right, there are no more table columns... A potential fix could be to fill in the empty space on the right with an empty table column.
![image](https://github.com/skadogg/personal-tv-guide/assets/26852517/bb7842e6-a54d-4e76-be98-b1ff14602cec)
