### ISSUE TITLE
♻ Refactor this code

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#52]
Before the next major version, I would like to go through and clean up the code. Specifically, the TV and movie scrapers are so similar, it would probably make sense to create some shared functions and combine the two into one file.

- [x] Combine scrape programs into new function
- [x] Document the "why" of the code
- [x] Update / standardize function names
- [x] Move user data to new folder

**Comment by code-master-ajay** [comment]
Hi @skadogg , i would also like to suggest that, instead of running three files one by one 

python scrape_tv.py
python scrape_movies.py
python create_genre_list.py

and waiting for each of them to finish so you can run the next one.

If we could just call a single command which will perform all three of these, that would be better.

what do you think ?

**Comment by skadogg** [comment]
I was also thinking about combining these files. The scrape_ files are _very_ similar, so I want to create some new functions so we don't have to maintain duplicate code. In the end, it would be great to have just one file to run everything.

**Comment by skadogg** [comment]
Fixed by #77
